## ¿Qué es NumPy?
* NumPy es un paquete de Python que provee un nuevo tipo de arreglos (otro tipo de $\textit{listas}$) que tienen la capacidad de almacenar y operar matemáticamente de manera eficiente
* Generalmente usado para cálculos científicos
* Arreglos de Numpy mucho más rápido que utilizar las listas nativas de Python

## Importando NumPy 

* Para importar NumPy simplemente hacemos:

In [ ]:
import numpy as np

* Jupyter Notebook nos ofrece la posibilidad de ver la documentación del paquete de la siguiente forma

In [ ]:
#np?

## Creando arreglos de NumPy




* Podemos crear arreglos de NumPy usando el método $\texttt{array}$ pasando como parámetro una lista nativa de Python

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

* No así como las listas nativas de Python, los arreglos de NumPy exigen que todos sus elementos sean del mismo tipo 

In [ ]:
np.array([1,2,3.2,4]) #convierte todos los enteros en float ya que 3.2 es float y los demas int

array([1. , 2. , 3.2, 4. ])

* También podemos crear arreglos de NumPy con métodos ya integrados en el paquete

In [ ]:
np.zeros(5, dtype=int) #crea un arreglo numpy de 10 ceros de tipo int

array([0, 0, 0, 0, 0])

In [ ]:
np.ones([2,3], dtype=int) #crea un arreglo multidimensional numpy 
                          #de 2 filas y 3 columnas de unos

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(0,10,2) #crea un arreglo numpy del 0 al 10 (sin incluir el 10) de 2 en 2

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,6) #crea un arreglo numpy con cinco valores espaciados uniformemente entre 0 y 1 inclusive

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
np.random.randint(0, 10, (2, 3)) #crea un arreglo multidimensional numpy de 2 filas y 3 columnas de numreos enteros al azar

array([[6, 0, 9],
       [5, 0, 2]])

## Accediendo a elementos individuales

* Similar a las listas de Python, utilizando el índice del elemento al que queramos acceder entre corchetes

In [ ]:
a = np.array([2,6,1,3,8,7])

In [ ]:
a[0]

2

In [ ]:
a[3]

3

In [ ]:
a[-1] #accediendo desde el final

7

* Para arreglos de dos dimensiones (matrices) se accede a los elementos usando el índice como una tupla

In [ ]:
b = np.reshape(a,(3,2)) #una forma de crear un array 2d es usando np.reshape en un arreglo de 1d
b

array([[2, 6],
       [1, 3],
       [8, 7]])

In [ ]:
b[0,0]

2

In [ ]:
b[1,1]

3

In [ ]:
b[-1,-1]

7

## Accediendo a sub-arreglos

* Podemos acceder a un sub-arreglo de un arreglo dado mediante la $\textit{slice}$ $\textit{notation}$  (notación de corte), denotada por el carácter ($\textbf{:}$)
* La sintaxis está dada por: $x[inicio:final:salto]$

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x[:5] #primeros 5 elementos

array([0, 1, 2, 3, 4])

In [ ]:
x[5:] #elementos del índice 5 en adelante

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x[3:6] #sub-arreglo del índice 3 al 6, (sin incluir el 6)

array([3, 4, 5])

In [ ]:
x[::-1] #arreglo inverso

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
x[::2] #de 2 en 2 partiendo de 0

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

* Para arreglos 2D es similar; debemos operar sobre las columnas y filas, utilizando la notación slice separada por comas

In [ ]:
y = np.reshape(np.arange(20),(4,5))
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
y[:1,:] #obteniendo la primera fila

array([[0, 1, 2, 3, 4]])

In [ ]:
y[:2,:2] #obteniendo la primera y segunda fila hasta la segunda columna

array([[0, 1],
       [5, 6]])

In [ ]:
y[::-1,::-1] #invierte la matriz

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## Concatenación y división de arreglos

* NumPy ofrece la posibilidad de unir arreglos y también de dividirlos

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

* Podemos concatenar más de dos arreglos al mismo tiempo

In [ ]:
z = np.arange(10)
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* También podemos usar $np.concatenate$ en arreglos 2D

In [ ]:
x = np.array([[1,2,3],
             [4,5,6]])

np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* Además, podemos dividir arreglos, usando una lista de índices donde indicamos los puntos de división

In [ ]:
x = np.arange(10)
np.split(x,(3,7)) #entrega una lista de arreglos, en donde el 1er elemento es del indice 0 al 2, el 2do del 3 al 6 y el 3ero del 7 al 9

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

## UFuncs de NumPy

* NumPy también provee operaciones sobre arreglos mucho más eficientes que las de las listas de Python, llamadas $\textbf{UFuncs}$ (Universal Functions)
* Sintaxis muy simple e intuitiva de usar

In [ ]:
x = np.arange(10)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) #divisón función piso

x = [0 1 2 3 4 5 6 7 8 9]
x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 2 = [ 0  2  4  6  8 10 12 14 16 18]
x / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
x // 2 = [0 0 1 1 2 2 3 3 4 4]


* También podemos utilizar éstas funciones como métodos de la librería

In [ ]:
print("x + 5 =", np.add(x,5))
print("x - 5 =", np.subtract(x,5))
print("x * 2 =", np.multiply(x,2))
print("x / 2 =", np.divide(x,2))
print("x // 5 =", np.floor_divide(x,2)) #divisón función piso

x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 2 = [ 0  2  4  6  8 10 12 14 16 18]
x / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
x // 5 = [0 0 1 1 2 2 3 3 4 4]


## Agregaciones


* Normalmente cuando tenemos una gran cantidad de datos a nuestra disposición, queremos extraer información estadísticamente significativa de éste.
* NumPy provee funciones de agregación eficientes a ser usadas en arreglos


In [ ]:
x = np.random.randint(0,10,10)
print("x:", x)
print("Suma de todos los elementos:", np.sum(x))
print("Promedio:", np.mean(x))
print("Desviación estándar:", np.std(x))
print("Varianza:", np.var(x))
print("Menor elemento: %.d y su índice: %.d" % (np.min(x),(np.argmin(x))))
print("Mayor elemento: %.d y su índice: %.d" % (np.max(x),(np.argmax(x))))

x: [6 5 3 9 8 3 5 8 3 5]
Suma de todos los elementos: 55
Promedio: 5.5
Desviación estándar: 2.1095023109728985
Varianza: 4.45
Menor elemento: 3 y su índice: 2
Mayor elemento: 9 y su índice: 3


## Enmascaramiento Booleano


* Una de las características más útiles y usadas de NumPy es el enmascaramiento booleano
* Nos sirve cuando queremos extraer datos de un arreglo basados en simples comparaciones con operadores booleanos o algún criterio
* La sintaxis viene dada por: $x$[alguna(s) comparación(es) booleana(s)]


In [ ]:
x = np.arange(1,21)
print("x:", x)
print("Todos los elementos mayores a 10:", x[x > 10])
print("Todos los elementos pares:", x[x % 2 == 0])
print("Todos los elementos negativos", x[x < 0])
print("Todos los elementos mayores a 10 o múltiplos de 4:", x[(x > 10) | (x % 4 == 0)])
print("Todos los elementos impares y múltiplos de 3:", x[~(x % 2 == 0) & (x % 3 == 0)])

x: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Todos los elementos mayores a 10: [11 12 13 14 15 16 17 18 19 20]
Todos los elementos pares: [ 2  4  6  8 10 12 14 16 18 20]
Todos los elementos negativos []
Todos los elementos mayores a 10 o múltiplos de 4: [ 4  8 11 12 13 14 15 16 17 18 19 20]
Todos los elementos impares y múltiplos de 3: [ 3  9 15]


## Arreglos Estructurados

* Generalmente, nuestros datos pueden estar bien representados usando arreglos con el mismo tipo de valores, pero no siempre es el caso

* NumPy ofrece lo que son llamados arreglos estructurados, los cuáles son un tipo de arreglo el cual provee almacenamiento y extracción eficiente de datos que no necesariamente tienen que ser del mismo tipo

In [ ]:
#Creamos los arreglos como listas de Python con los datos que queramos almacenar
nombres = ['Pepe','Juan','María']
carreras = ['Ingeniería Civil Informática','Ingeniería Civil Eléctrica','Ingeniería Civil']
promedios = [59,74,61]

#Usando np.zeros creamos un arreglo con 3 ceros, excepto que esta vez especificamos el nombre de los "índices" que queremos para luego acceder a ellos
#y el formato que queremos para los datos que almacenaremos
#en este caso, U10 son strings de largo no más de 10, U30 de largo no más de 30 y i4 enteros de 4 bytes
datos = np.zeros(3, dtype={'names':('nombre', 'carrera', 'promedio'),'formats':('U10', 'U30', 'i4')})
print(datos.dtype) 

#Ahora solo queda asignar a nuestro nuevo arreglo estructural las listas creadas anteriormente
datos['nombre'] = nombres
datos['carrera'] = carreras
datos['promedio'] = promedios
print(datos)

[('nombre', '<U10'), ('carrera', '<U30'), ('promedio', '<i4')]
[('Pepe', 'Ingeniería Civil Informática', 59)
 ('Juan', 'Ingeniería Civil Eléctrica', 74)
 ('María', 'Ingeniería Civil', 61)]


* Podemos acceder a los datos almacenados usando una sintaxis similar a la de diccionarios en Python o usando índices enteros

In [ ]:
print("Todos los nombres:", datos['nombre'])
print("Primera fila con todos los datos:", datos[0])
print("Promedio de la persona en la segunda fila:", datos[1]['promedio'])

Todos los nombres: ['Pepe' 'Juan' 'María']
Primera fila con todos los datos: ('Pepe', 'Ingeniería Civil Informática', 59)
Promedio de la persona en la segunda fila: 74


* Además, podemos usar enmascaramiento booleano para poder filtrar datos en nuestro arreglo

In [ ]:
print("Personas con promedio mayor a 60:", datos['nombre'][datos['promedio'] > 60])
print("Todos los datos de los que estudian Ingeniería Civil:", datos[datos['carrera'] == 'Ingeniería Civil'])

Personas con promedio mayor a 60: ['Juan' 'María']
Todos los datos de los que estudian Ingeniería Civil: [('María', 'Ingeniería Civil', 61)]
